# Generated by Django 4.2.6 on 2024-06-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
