# Generated by Django 4.2.6 on 2024-06-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
