# Generated by Django 4.2.6 on 2024-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_outside_of_illinois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideofillinois',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outsideofillinois',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
