# Generated by Django 4.2.6 on 2024-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='cvv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='end_date',
            field=models.CharField(max_length=255),
        ),
    ]
