# Generated by Django 4.2.6 on 2024-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_cvv_alter_billing_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
