version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - ./.env

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c 'python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - media_volume:/app/media

volumes:
  media_volume:
  static_volume:
  postgres_data:

networks:
  my-network: