# Generated by Django 4.2.6 on 2024-06-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_unique_id_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
