# Generated by Django 4.2.6 on 2024-04-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('catalog_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsite',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country'),
        ),
    ]
