# Generated by Django 4.2.6 on 2024-04-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('icon', models.ImageField(upload_to='country_icons/')),
            ],
        ),
    ]
