# Generated by Django 4.2.6 on 2024-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchase_purchase_image_2_alter_purchase_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
