# Generated by Django 4.2.6 on 2024-06-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchase_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-id',)},
        ),
    ]
