# Generated by Django 4.2.6 on 2024-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status_request',
            field=models.BooleanField(default=False),
        ),
    ]
