# Generated by Django 4.2.6 on 2024-06-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('warehouses', '0012_warehouseproduct_status_many'),
        ('my_warehouse', '0002_mywarehouse_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywarehouse',
            name='country_of_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_my_warehouseproducts', to='countries.country'),
        ),
        migrations.AddField(
            model_name='mywarehouse',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_my_warehouseproducts', to='countries.country'),
        ),
        migrations.AlterField(
            model_name='mywarehouse',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
    ]
