# Generated by Django 4.2.6 on 2024-04-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0)),
                ('track_number', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('unique_id_user', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouse/')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.status')),
            ],
        ),
    ]
