# Generated by Django 4.2.6 on 2024-04-07 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='articul',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='color',
            field=models.CharField(default='default-color', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
