# Generated by Django 4.2.6 on 2024-04-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_warehouse_articul_warehouse_color_warehouse_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.statuspayment'),
        ),
    ]
