# Generated by Django 4.2.6 on 2024-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_statuspayment_warehouse_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='color',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='count',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='date_arrived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_parcels',
            field=models.BooleanField(default=False),
        ),
    ]
