# Generated by Django 4.2.6 on 2024-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_remove_warehouse_color_remove_warehouse_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='date_arrived',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='date_sent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
