# Generated by Django 4.2.6 on 2024-06-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('warehouses', '0005_alter_warehouse_date_arrived_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='WarehouseProduct',
        ),
    ]
