# Generated by Django 4.2.6 on 2024-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_remove_warehouseproduct_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='articul',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
