# Generated by Django 4.2.6 on 2024-06-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_alter_warehouseproduct_articul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
