# Generated by Django 4.2.6 on 2024-06-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0009_alter_warehouseproduct_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse/'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse_product/'),
        ),
    ]
