# Generated by Django 4.2.6 on 2024-07-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_back_image_address_email_address_front_image_and_more'),
        ('warehouses', '0012_warehouseproduct_status_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
