# Generated by Django 4.2.6 on 2024-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0013_warehouseproduct_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='image_check',
            field=models.ImageField(blank=True, null=True, upload_to='image_check/'),
        ),
    ]
