# Generated by Django 4.2.6 on 2024-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
    ]
